remove linter from script
Signed-off-by: Michael Robinson <merobi@gmail.com>

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -37,12 +37,10 @@ jobs:
                 ok=0
                 echo "Copyright header not found in $file"
               fi
-            else 
-              if [[ ($file == *".java") ]]; then
-                if ! grep -q Copyright "$file"; then
-                  ok=0
-                  echo "Copyright header not found in $file"
-                fi
+            elif [[ ($file == *".java") ]]; then
+              if ! grep -q Copyright "$file"; then
+                ok=0
+                echo "Copyright header not found in $file"
               fi
             fi
           if [[ $ok == 0 ]]; then
