remove linter from script
Signed-off-by: Michael Robinson <merobi@gmail.com>

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -1,5 +1,5 @@
 ---
-name: Lint Code Base
+name: Check for Headers in Source Code
 
 on:
   push:
@@ -9,18 +9,10 @@ on:
 
 jobs:
   build:
-    name: Lint Code Base
+    name: Check for Headers
     runs-on: ubuntu-latest
 
     steps:
-      # - name: Install dependencies
-      #   run: |
-      #     python -m pip install --upgrade pip
-      #     pip install pylint==2.14.3
-      #     pip install astroid==2.11.6
-      #     pip install typing_extensions==4.0.1
-      #     pip install importlib-metadata==4.11.3
-
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
@@ -47,6 +39,12 @@ jobs:
               fi
             fi
           done
+            if [[ ($file == *".java") ]]; then
+              if ! grep -q Copyright "$file"; then
+                ok=0
+                echo "Copyright header not found in $file"
+              fi
+            fi
           if [[ $ok == 0 ]]; then
             exit 1
           fi           
