remove linter from script
Signed-off-by: Michael Robinson <merobi@gmail.com>

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -41,9 +41,9 @@ jobs:
           readarray -t files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.all }}')"
           for file in ${files[@]}; do 
             if [[ ($file == *".py") ]]; then
-              if ! grep -q Copyright "$file";
+              if ! grep -q Copyright "$file"; then
                 $ok=false
-                echo "Copyright header not found in $file";
+                echo "Copyright header not found in $file"
               fi
             fi
           done
